name: Hello Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello, Actions!"
  greet2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello, Actions! 2"

  terraform:
    run-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with: terraform_version: "1.1.7"
    - run: terraform init       
